[build]
  functions = "functions"
  publish = "public"
  
[dev]
  functions = "functions"

[[redirects]]
  from = "/movie/*"
  to = "/.netlify/functions/videoHandler/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200
